platform:
  sepolicy_dirs:
    - device/google/redbull-sepolicy

includes:
  - common.yml

filters:
  partitions:
    match:
      # TODO: add support for OTA firmware partitions
      - xbl
      - xbl_config
      - aop
      - tz
      - hyp
      - abl
      - keymaster
      - devcfg
      - qupfw
      - uefisecapp
      - featenabler
      - logfs
      - modem

  dep_files:
    match:
      # Required by libOmxSwVencMpeg4
      - vendor/lib/libMpeg4SwEncoder.so
      - vendor/lib64/libMpeg4SwEncoder.so

      # Required by vendor.qti.hardware.display.composer-service
      - vendor/lib64/libthermalclient.so

      # Required by chre
      - vendor/lib/libadsprpc.so
      - vendor/lib64/libadsprpc.so

      # Required by libOmxVenc
      - vendor/lib/libfastcvopt.so
      - vendor/lib64/libfastcvopt.so

      # Required for compatibility matrix
      #- vendor/etc/vintf/manifest/c2_manifest_vendor.xml
